/* 
 * Copyright 2019 Michael Büchner, Deutsche Digitale Bibliothek
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.ddb.labs.beagen;

import de.ddb.labs.beagen.backend.BeaconFile;
import de.ddb.labs.beagen.backend.BeaconFileController;
import de.ddb.labs.beagen.backend.helper.Configuration;
import de.ddb.labs.beagen.backend.helper.EntityManagerUtil;
import de.ddb.labs.beagen.backend.jobs.BeaconJob;
import de.ddb.labs.beagen.backend.data.SECTOR;
import de.ddb.labs.beagen.backend.data.TYPE;
import io.javalin.BadRequestResponse;
import io.javalin.Context;
import io.javalin.Javalin;
import io.javalin.JavalinEvent;
import io.javalin.NotFoundResponse;
import java.util.List;
import org.quartz.CronScheduleBuilder;
import org.quartz.JobBuilder;
import org.quartz.JobDetail;
import org.quartz.Scheduler;
import org.quartz.Trigger;
import org.quartz.TriggerBuilder;
import org.quartz.impl.StdSchedulerFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author buechner
 */
public class Main {

    // Logger
    private static final Logger LOG = LoggerFactory.getLogger(Main.class);

    // Job Scheduler
    private static Scheduler quartzScheduler;

    /**
     * Main entry point which starts a local http server listening on port 80.
     *
     * @param args
     * @throws Exception
     */
    public static void main(String[] args) throws Exception {

        // set env
        if (System.getProperty("beagen.log.dir") == null) {
            System.setProperty("beagen.log.dir", Configuration.get().getValue("beagen.log.dir"));
        }
        if (System.getProperty("beagen.database.dir") == null) {
            System.setProperty("beagen.database.dir", Configuration.get().getValue("beagen.database.dir"));
        }
        if (System.getProperty("beagen.baseurl") == null) {
            System.setProperty("beagen.baseurl", Configuration.get().getValue("beagen.baseurl"));
        }
        if (System.getProperty("beagen.cron") == null) {
            System.setProperty("beagen.cron", Configuration.get().getValue("beagen.cron"));
        }
        if (System.getProperty("beagen.ddbapikey") == null) {
            System.setProperty("beagen.ddbapikey", Configuration.get().getValue("beagen.ddbapikey"));
        }

        // log env
        LOG.info("ENV set beagen.log.dir={}", System.getProperty("beagen.log.dir"));
        LOG.info("ENV set beagen.database.dir={}", System.getProperty("beagen.database.dir"));
        LOG.info("ENV set beagen.baseurl={}", System.getProperty("beagen.baseurl"));
        LOG.info("ENV set beagen.cron={}", System.getProperty("beagen.cron"));
        LOG.info("ENV set beagen.ddbapikey={}", System.getProperty("beagen.ddbapikey"));

        // start update job
        final JobDetail job = JobBuilder.newJob(BeaconJob.class)
                .withIdentity("cronjob", "crongroup")
                .build();

        final Trigger trigger = TriggerBuilder.newTrigger()
                .withIdentity("crontrigger", "crongroup")
                .startNow()
                .withSchedule(CronScheduleBuilder.cronSchedule(System.getProperty("beagen.cron")))
                .build();

        quartzScheduler = new StdSchedulerFactory().getScheduler();
        quartzScheduler.start();
        quartzScheduler.scheduleJob(job, trigger);

        // start javalin server
        final Javalin app = Javalin.create()
                .enableAutogeneratedEtags()
                .enableCorsForAllOrigins()
                .disableStartupBanner()
                // .enableStaticFiles("/")
                .event(JavalinEvent.SERVER_STARTING, () -> {
                    EntityManagerUtil.getInstance(); // init DB
                })
                .event(JavalinEvent.SERVER_STOPPED, () -> {
                    EntityManagerUtil.getInstance().shutdown(); // close DB connection
                })
                .start(80);

        // set UTF-8 as default charset
        app.before(ctx -> {
            ctx.res.setCharacterEncoding("UTF-8");
        });

        app.get("/item/:id", ctx -> {
            final Long id = Long.parseLong(ctx.pathParam("id"));
            final BeaconFile bfile = BeaconFileController.getBeaconFile(id);
            if (bfile == null) {
                throw new NotFoundResponse("Beacon-Datei " + id + " nicht gefunden");
            }
            ctx.result(bfile.getBeaconFile());
        });

        app.get("/item/:type/:sector/latest", ctx -> {

            TYPE type;
            try {
                type = TYPE.valueOf(ctx.pathParam("type").toUpperCase());
            } catch (Exception e) {
                throw new BadRequestResponse("Kein gültiger Typ");
            }

            SECTOR sector;
            try {
                sector = SECTOR.valueOf(ctx.pathParam("sector").toUpperCase());
            } catch (Exception e) {
                throw new BadRequestResponse("Keine gültige Kultursparte");
            }

            final List<BeaconFile> bfileList = BeaconFileController.getBeaconFiles(type, sector, true);
            if (bfileList.size() > 0) {
                final BeaconFile bfile = bfileList.get(0);
                //ctx.contentType("text/plain");
                ctx.result(bfile.getBeaconFile());
            } else {
                throw new NotFoundResponse("Keine Beacon-Datei gefunden");
            }
        });

        app.get("/", ctx -> {
            final String prefix = ctx.req.getHeader("X-Forwarded-Prefix");
            ctx.redirect(((prefix != null && !prefix.isEmpty()) ? prefix : "") + "/list/latest?type=organisation&sector=all", 301);
        });

        app.get("/list", ctx -> {
            deliver(ctx, false);
        });

        // set paths
        app.get("/list/latest", ctx -> {
            deliver(ctx, true);
        });
    }

    private static void deliver(Context ctx, boolean latest) {
        if (deliverHtml(ctx.req.getHeader("Accept"))) {
            ctx.render("/base.mustache");
            return;
        }

        TYPE type;
        try {
            final String t = ctx.queryParam("type") == null ? "organisation" : ctx.queryParam("type");
            type = TYPE.valueOf(t.toUpperCase());
        } catch (Exception e) {
            throw new BadRequestResponse("Kein gültiger Typ");
        }

        SECTOR sector;
        try {
            final String s = ctx.queryParam("sector") == null ? "all" : ctx.queryParam("sector");
            sector = SECTOR.valueOf(s.toUpperCase());
        } catch (Exception e) {
            throw new BadRequestResponse("Keine gültige Kultursparte");
        }

        if (type != null || sector != null) {
            ctx.json(BeaconFileController.getBeaconFiles(type, sector, latest));

        } else {
            ctx.json(BeaconFileController.getBeaconFiles(null, latest));
        }
    }

    private static boolean deliverHtml(String accept) {
        if (accept == null) {
            return true;
        }
        accept = accept.substring(0, accept.indexOf(';') == -1 ? accept.length() : accept.indexOf(';'));
        final String[] mimeTypes = accept.split(",");

        for (int i = 0; i < mimeTypes.length; ++i) {
            if (mimeTypes[i].trim().equalsIgnoreCase("text/html")) {
                return true;
            }
            if (mimeTypes[i].trim().equalsIgnoreCase("application/xhtml+xml")) {
                return true;
            }
            if (mimeTypes[i].trim().equalsIgnoreCase("application/json")) {
                return false;
            }
            if (mimeTypes[i].trim().equalsIgnoreCase("text/javascript")) {
                return false;
            }
        }

        return false;
    }
}
